name: LaTeX to PDF

on:
  push:
    branches: 
      - master
      - release/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: check sectet token
        run: echo ${{ sectets.GITHUB_TOKEN }}
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build docker image
        uses: peano-system/nugitlecture/.github/actions/latex@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
